Data:
    train_dir: Data/train
    val_dir: Data/val
    image_size: [224, 224]
    num_workers: 8
    pin_memory: true
    batch_size: 2
    drop_last: true

Pipeline:
    name: ijepa
    backbone: 'vit_base_patch16'
    patch_size: 16
    in_chans: 3
    img_size: 224
    embed_dim: 768
    layers: 12
    heads: 12
    mlp_ratio: 4.0
    context_size: 8
    target_size: 4
    projector_dim: 512
    projector_depth: 2
    mask:
        strategy: 'block'
        mask_ratio: 0.5

Training:
    epochs: 800
    val_every_n_epoch: 50
    optimizer:
        name: 'adamw'
        lr: 0.0005
        warmup_epochs: 20
        start_factor: 0.1
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.05
        eta_min: 1e-05

Logging:
    project: 'simgroupattn_v2'
    entity: 'wwy'
    checkpoint_path: 'CHECKPOINTS/ijepa'
    save_every_n_epoch: 50
    num_samples: 0
